### PR TITLE
Fix #1091

### LINKED ISSUE #1091: Custom mutation throws: "Cannot read property 'args' of undefined"
**Describe the bug**
Custom mutation throws the following error.

```
TypeError: Cannot read property 'args' of undefined
[run:server]     at ValidateCustomFieldsInterceptor.getArgumentMap (/app/node_modules/@vendure/core/src/api/middleware/validate-custom-fields-interceptor.ts:133:45)
[run:server]     at ValidateCustomFieldsInterceptor.intercept (/app/node_modules/@vendure/core/src/api/middleware/validate-custom-fields-interceptor.ts:50:45)
[run:server]     at /app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
[run:server]     at Object.handle (/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:21:56)
[run:server]     at IdInterceptor.intercept (/app/node_modules/@vendure/core/src/api/middleware/id-interceptor.ts:38:21)
[run:server]     at /app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
[run:server]     at InterceptorsConsumer.intercept (/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
[run:server]     at target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:76:60)
[run:server]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[run:server]     at /app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

**To Reproduce**

1.
Define custom API extension (shop api)

```graphql
extend type Mutation {
  doSomething: ActiveOrderResult!
}
```

2. Invoke this mutation in production 
(`shopApiDebug: false` in vendure config - doesnt seem to be happening locally when developing)
3. See error

**Expected behavior**
No error. Seems this started with migration to Vendure 1.2.0 (worked before)

**Environment (please complete the following information):**
 - @vendure/core version: 1.2.1
 - Nodejs version: 14.17
 - Database (mysql/postgres etc): postgres

### PR DESCRIPTION
**Pull request by filipproch**
Fixes #1091

### CODE REVIEW

File: packages/core/src/api/middleware/validate-custom-fields-interceptor.ts [hunk 1]
```diff
@@ -127,7 +127,7 @@ export class ValidateCustomFieldsInterceptor implements NestInterceptor {
         const map: { [inputName: string]: string } = {};
 
         for (const selection of operation.selectionSet.selections) {
-            if (selection.kind === 'Field') {
+            if (selection.kind === 'Field' && !selection.name.value.startsWith('__')) {
```
Comment (michaelbromley) [inline packages/core/src/api/middleware/validate-custom-fields-interceptor.ts]: Can we be sure that this will not have unintended consequences? E.g. what if I name my custom field `'__mrp'`?

Is there an argument against checking for the full string `'__typename'`?

Comment (filipproch) [reply packages/core/src/api/middleware/validate-custom-fields-interceptor.ts]: GraphQL is using "__" in various places for internal field.

https://graphql.org/learn/introspection/
or 
__resolveType

so I felt to future proof it in case there would be some additions to GraphQL spec in the future

Comment (filipproch) [reply packages/core/src/api/middleware/validate-custom-fields-interceptor.ts]: if you prefer just __typename - I will change it

Comment (michaelbromley) [reply packages/core/src/api/middleware/validate-custom-fields-interceptor.ts]: I just had another thought - perhaps a way to avoid the entire issue with the naming convention is to just make the function ignore an undefined `inputType` on line 133, with `const arg of inputType?.args ?? []`.

**Comment by filipproch** [comment]
Sure will try it and update the PR

On October 20, 2021, GitHub ***@***.***> wrote:
> @michaelbromley commented on this pull request.
>

> In packages/core/src/api/middleware/validate-custom-fields-
> interceptor.ts <https://github.com/vendure-
> ecommerce/vendure/pull/1178#discussion_r732718666>:
>

> @@ -127,7 +127,7 @@ export class ValidateCustomFieldsInterceptor
implements NestInterceptor { const map: { [inputName: string]: string }
= {}; for (const selection of operation.selectionSet.selections) { - if
(selection.kind === 'Field') { + if (selection.kind === 'Field' &&
!selection.name.value.startsWith('__')) {
> I just had another thought - perhaps a way to avoid the entire issue
> with the naming convention is to just make the function ignore an
> undefined inputType on line 133, with const arg of inputType?.args ??
> [].
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vendure-
ecommerce/vendure/pull/1178#discussion_r732718666>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAKSU3AOYAWSFG2UMGUHV73UH2YCBANCNFSM5GLMEZSQ>.

File: packages/core/src/api/middleware/validate-custom-fields-interceptor.ts (hunk 1 above)
Comment (filipproch) [reply packages/core/src/api/middleware/validate-custom-fields-interceptor.ts]: done
